/// <reference types="vite-plugin-svgr/client" />
export { ReactComponent as ApolloSvg } from '@/assets/skills/apollo.svg'
export { ReactComponent as CssSvg } from '@/assets/skills/css.svg'
export { ReactComponent as ExpressSvg } from '@/assets/skills/express.svg'
export { ReactComponent as GraphqlSvg } from '@/assets/skills/graphql.svg'
export { ReactComponent as HtmlSvg } from '@/assets/skills/html.svg'
export { ReactComponent as JavascriptSvg } from '@/assets/skills/javascript.svg'
export { ReactComponent as MaterialUISvg } from '@/assets/skills/materialUI.svg'
export { ReactComponent as NestSvg } from '@/assets/skills/nest.svg'
export { ReactComponent as NextSvg } from '@/assets/skills/next.svg'
export { ReactComponent as NodeSvg } from '@/assets/skills/node.svg'
export { ReactComponent as ReactSvg } from '@/assets/skills/react.svg'
export { ReactComponent as SassSvg } from '@/assets/skills/sass.svg'
export { ReactComponent as TailwindSvg } from '@/assets/skills/tailwind.svg'
export { ReactComponent as TypescriptSvg } from '@/assets/skills/typescript.svg'
export { ReactComponent as CvSvg } from '@/assets/cv.svg'
